osx_image: xcode7.3
language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage update --platform iOS
#- travis_wait 35 carthage update --platform iOS,Mac

script:
- xcodebuild clean build -project GithubSwift.xcodeproj -scheme GithubSwift-iOS -sdk iphonesimulator
- xcodebuild test -project GithubSwift.xcodeproj -scheme GithubSwift-iOS -sdk iphonesimulator
#- xcodebuild clean build -project GithubSwift.xcodeproj -scheme GithubSwift-Mac -sdk macosx
#- xcodebuild test -project GithubSwift.xcodeproj -scheme GithubSwift-Mac -sdk macosx